name: Nuget Preview Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push to Github NBasis.Lambda
      run: dotnet nuget push NBasis.Lambda.${VERSION}.nupkg --source https://nuget.pkg.github.com/shawnspeak/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to Github NBasis.Lambda.Serilog
      run: dotnet nuget push NBasis.Lambda.Serilog.${VERSION}.nupkg --source https://nuget.pkg.github.com/shawnspeak/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to Github NBasis.Lambda.RuntimeSupport
      run: dotnet nuget push NBasis.Lambda.RuntimeSupport.${VERSION}.nupkg --source https://nuget.pkg.github.com/shawnspeak/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to Nuget NBasis.Lambda
      run: dotnet nuget push NBasis.Lambda.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    - name: Push to Nuget NBasis.Lambda.Serilog
      run: dotnet nuget push NBasis.Lambda.Serilog.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
    - name: Push to Nuget NBasis.Lambda.RuntimeSupport
      run: dotnet nuget push NBasis.Lambda.RuntimeSupport.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}